### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by lmxiaonuo** [scipopt/JSCIPOpt#10]
when I run scip like this in my mac pro

`java -cp scip.jar:examples.jar Linear`

I've found that an exception has been threw in my terminal

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000128d7a241, pid=19480, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libawt_lwawt.dylib+0x46241]  JNI_OnLoad+0x91
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/muzhe/Documents/temp/JSCIPOpt/build/Release/hs_err_pid19480.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6
```

```
the internal exception 
Internal exceptions (2 events):
Event: 0.030 Thread 0x00007faad780c800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x000000076ab07ca8) thrown at [/Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u121/8372/hotspo
Event: 0.030 Thread 0x00007faad780c800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x000000076ab07f90) thrown at [/Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u121/8372/hotspot/src/share/vm/pri

Stack: [0x00007000082d8000,0x00007000083d8000],  sp=0x00007000083d7480,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [liblwawt.dylib+0xe17b]  JNI_OnLoad+0x91
C  [libjava.dylib+0x1443]  Java_java_lang_ClassLoader_00024NativeLibrary_load+0xcf
j  java.lang.ClassLoader$NativeLibrary.load(Ljava/lang/String;)V+0
j  java.lang.ClassLoader.loadLibrary1(Ljava/lang/Class;Ljava/io/File;)Z+302
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+2
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+268
j  java.lang.Runtime.loadLibrary0(Ljava/lang/Class;Ljava/lang/String;)V+54
j  java.lang.System.loadLibrary(Ljava/lang/String;)V+7
j  Linear.main([Ljava/lang/String;)V+2
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x2dc898]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x22a
V  [libjvm.dylib+0x2dc668]  JavaCalls::call(JavaValue*, methodHandle, JavaCallArguments*, Thread*)+0x28
V  [libjvm.dylib+0x31004e]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0xe6
V  [libjvm.dylib+0x3091e9]  jni_CallStaticVoidMethod+0x10b
C  [java+0x30fe]  JavaMain+0x91d
C  [libsystem_pthread.dylib+0x39af]  _pthread_body+0xb4
C  [libsystem_pthread.dylib+0x38fb]  _pthread_body+0x0
C  [libsystem_pthread.dylib+0x3101]  thread_start+0xd

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load(Ljava/lang/String;)V+0
j  java.lang.ClassLoader.loadLibrary1(Ljava/lang/Class;Ljava/io/File;)Z+302
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+2
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+268
j  java.lang.Runtime.loadLibrary0(Ljava/lang/Class;Ljava/lang/String;)V+54
j  java.lang.System.loadLibrary(Ljava/lang/String;)V+7
j  Linear.main([Ljava/lang/String;)V+2
v  ~StubRoutines::call_stub
```

please help me!

**Comment by mueldgog** [comment]
I need more information in order to help you. Can you write, step by step, how you compiled the SCIP Optimization Suite and JSCIPOpt? Please list all executed commands. Which C compiler did you use? I am guessing that you are using a MAC, right?

**Comment by lmxiaonuo** [comment]
cmake .. -DSCIP_DIR=/Users/muzhe/Downloads/scipoptsuite-5.0.0/build

```
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found JNI: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libjawt.dylib  
-- Found Java: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (found version "1.8.0.121") 
-- Found SWIG: /usr/local/bin/swig (found version "3.0.12") 
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   jscip

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/muzhe/Downloads/JSCIPOpt/build
```

make

```
Scanning dependencies of target scipjar
[ 10%] Building Java objects for scipjar.jar
[ 20%] Generating Release/CMakeFiles/scipjar.dir/java_class_filelist
[ 30%] Creating Java archive scip.jar
[ 40%] Built target scipjar
Scanning dependencies of target examples
[ 50%] Building Java objects for examples.jar
[ 60%] Generating Release/CMakeFiles/examples.dir/java_class_filelist
[ 70%] Creating Java archive examples.jar
[ 70%] Built target examples
Scanning dependencies of target jscip
[ 80%] Building C object CMakeFiles/jscip.dir/src/scipjni_wrap.c.o
[ 90%] Linking C shared library Release/libjscip.dylib
ld: warning: directory not found for option '-L/Users/muzhe/Downloads/JSCIPOpt/lib'
[100%] Built target jscip

```
java -cp scip.jar:examples.jar "Linear"

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000123570241, pid=61158, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libawt_lwawt.dylib+0x46241]  JNI_OnLoad+0x91
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/muzhe/Downloads/JSCIPOpt/build/Release/hs_err_pid61158.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6
```

**Comment by lmxiaonuo** [comment]
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by lmxiaonuo** [comment]
the information you need is shown above, thanks a lot

**Comment by lmxiaonuo** [comment]
BTW i can use pyscipopt

**Comment by lmxiaonuo** [comment]
another problem, how can I get dual solution from JSCIPOpt

**Comment by mueldgog** [comment]
Hi,
I am currently on vacation and will be back on January 4th.

Regards

Am 27.12.2017 06:13 schrieb "lmxiaonuo" <notifications@github.com>:

**Comment by mcarreiro** [comment]
Hi, 
I have the same issue. Did you ever resolve it?

**Comment by mueldgog** [comment]
No, I couldn't reproduce this bug so far. @mcarreiro, do you also compile JSCIPOpt on a MAC?

**Comment by mueldgog** [comment]
@mcarreiro, can you check whether one of the following java commands work?
```
java -classpath "scip.jar:examples.jar" "Linear"
java -Djava.class.path=scip.jar:examples.jar "Linear"
```

Thanks!

**Comment by JianzhouZhan** [comment]
Hi, I have the same issue. I also compile JSCIPOpt on Mac Pro.

**Comment by JianzhouZhan** [comment]
`java -classpath "scip.jar:examples.jar" "Linear"
java -Djava.class.path=scip.jar:examples.jar "Linear"`

Result:
`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011d78e309, pid=4709, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libawt_lwawt.dylib+0x48309]  JNI_OnLoad+0x91
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/didi/Downloads/DownloadsLibrary/JSCIPOpt-master/build/Release/hs_err_pid4709.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#`

**Comment by liuqiyun** [comment]
@mueldgog  I also encountered such issue, my jdk version is 1.8.0_211-b12, and am waiting the solution...

**Comment by mengxz188** [comment]
Hi, I have the same issue. I also compile JSCIPOpt on Mac Pro.

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001160dd369, pid=13742, tid=0x0000000000000d03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libawt_lwawt.dylib+0x47369]  JNI_OnLoad+0x91
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/mengxiangzhe/IdeaProjects/wtf-route/algo/hs_err_pid13742.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by mengxz188** [comment]
Hi, I have the same issue. I also compile JSCIPOpt on Mac Pro.

 
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00000001160dd369, pid=13742, tid=0x0000000000000d03

 JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode bsd-amd64 compressed oops)
 Problematic frame:
 C  [libawt_lwawt.dylib+0x47369]  JNI_OnLoad+0x91

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /Users/mengxiangzhe/IdeaProjects/wtf-route/algo/hs_err_pid13742.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by kkofler** [comment]
Since commit 468efd0a36d72aab7295fa79b363e41317ce8a75, we no longer link the AWT JNI library, which should fix this bug. Also, there is a comment claiming that using a newer JDK (10 instead of 8) fixes it too.

**Comment by kkofler** [comment]
(Actually, we have not been linking it since commit 49e832b17d59f7bc84a5eb2f8bf5235d626c141d already. The later commit then also stopped searching at build time for the library we do not need.)
