### ISSUE TITLE
error when build scip-7.0 on windows

### ISSUE THREAD

**Issue by bithwb** [scipopt/JSCIPOpt#25]
i run 
cmake ..
got 
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.24.28316.0
-- The CXX compiler identification is MSVC 19.24.28316.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find GMP (missing: GMP_INCLUDE_DIRS GMP_LIBRARIES)
SoPlex with Boost CPP multiprecision libraries.
-- Performing Test Quadmath_USE_DIRECTLY
-- Performing Test Quadmath_USE_DIRECTLY - Failed
-- Could NOT find Quadmath (missing: Quadmath_LIBRARY Quadmath_INCLUDE_DIR)
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) (Required is at least version "1.58.0")
CMake Warning at soplex/CMakeLists.txt:162 (message):
  Boost could not be found! ONLY the SoPlex library can be built without
  Boost.  The SoPlex binary will NOT be built.  If you require the binary,
  please make sure Boost is installed and your BOOST_ROOT environment
  variable is set.

CMake Error at soplex/check/CMakeLists.txt:66 (if):
  if given arguments:

    "GREATER_EQUAL" "107000"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "E:/github/scipoptsuite-7.0.0/build/CMakeFiles/CMakeOutput.log".
See also "E:/github/scipoptsuite-7.0.0/build/CMakeFiles/CMakeError.log".

**Comment by mueldgog** [comment]
Can you upgrade your CMake to the latest version? I think this should work with newer versions of CMake.

**Comment by kkofler** [comment]
Not a JSCIP issue and probably fixed in newer CMake versions, closing.
