### ISSUE TITLE
Accessing model or solution status

### ISSUE THREAD

**Issue by patrickguenther** [scipopt/JSCIPOpt#37]
Is there a way to programmatically get the status of the model after Scip::solve has been called? For example, if an optimal solution has been found or if the model is unbounded or infeasible?

**Comment by kkofler** [comment]
As far as I can tell, no, that is still missing in the Java binding. We need to add `SCIPgetStatus` (https://scipopt.org/doc/html/group__GeneralSCIPMethods.php#gadfa940b47f19c0863d400b554378ef45) and the `SCIP_STATUS` type to `scipjni.i`.

**Comment by patrickguenther** [comment]
Interesting, is this something I can try on my own? how does this work? So this scipjni.i is the entry file for SWIG?
I think there might have been some other functionality of the SCIP API that I was missing as well.

**Comment by patrickguenther** [comment]
I've found the corresponding README.md section https://github.com/scipopt/JSCIPOpt#how-to-extend-the-interface and I give it a try.
