### ISSUE TITLE
The import scip cannot be resolved Java(268435846)

### ISSUE THREAD

**Issue by RohitGanji** [scipopt/JSCIPOpt#46]
I've followed the steps on the documentation for macOS but looks like my Java environment is unable to detect scip.

Did the manual installation with optimization suit as well. Is it supposed to generate scip.jar or jscip.jar?

**Comment by kkofler** [comment]
`scip.jar`

**Comment by RohitGanji** [comment]
How do I import it in Java? I'm trying to solve an optimization problem

**Comment by kkofler** [comment]
```java
import jscip.*;
```

Please see the examples in the folder `example` in this repository.

You will also need to have `scip.jar` in your classpath (for which it depends on your build system how to set that up) and the JNI libraries in a place where they will be found (which depends on the operating system and the used JRE/JDK).

This is not a place for basic Java support questions.

**Comment by kkofler** [comment]
FYI, depending on the JRE, the JNI library search path may or may not include any of:
* the system library search path of your operating system (which may or may not be tunable through environment variables),
* the Java classpath,
* the current working directory.
