### ISSUE TITLE
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: 'void jscip.SCIPJNIJNI.swig_module_init()'

### ISSUE THREAD

**Issue by hulizong** [scipopt/JSCIPOpt#51]
SCIP Optimization Suite:scipoptsuite-8.0.0.tgz

Execute command ‘make’ ，found libscip.so in build/lib

use libscip.so  in java and deploy the  jar on Ubuntu 22.04.5 LTS

An error occurred when I called the following code
scip =  new Scip();
System.load(JScip_Path);
scip.create("Test");

Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: 'void jscip.SCIPJNIJNI.swig_module_init()'
        at jscip.SCIPJNIJNI.swig_module_init(Native Method)
        at jscip.SCIPJNIJNI.<clinit>(SCIPJNIJNI.java:234)
        at jscip.SCIPJNI.createSCIP(SCIPJNI.java:461)
        at jscip.Scip.create(Scip.java:24)

**Comment by hulizong** [comment]
I just started ,I don't quite understand what you mean
How can I use this in Java on Linux?
i see the document : https://github.com/scipopt/JSCIPOpt/blob/master/INSTALL.md
How should I use the compiled file correctly?
I only found libscip.so in the scipoptsuite-8.0.0/build/lib
![image](https://github.com/user-attachments/assets/1ae49b30-63be-42eb-82e0-d471b1c581ab)

**Comment by kkofler** [comment]
> I just started ,I don't quite understand what you mean
> How can I use this in Java on Linux?

This is an issue tracker, not a support forum.

> How should I use the compiled file correctly?
> I only found libscip.so in the scipoptsuite-8.0.0/build/lib

You compiled scipoptsuite (step 1 in the document you linked), now you need to compile JSCIPOpt (step 2).
